In [1]:
import pandas as pd

# 2 Series

In [4]:
# 生成一个Series

ser_obj = pd.Series(range(10, 20)) #默认索引是0-9
print(ser_obj) #打印输出会带有类型

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64


In [6]:
print('-'*50)
# 获取数据
print(ser_obj.values)  #values实际是ndarray
print(type(ser_obj.values)) #类型是ndarray
# 获取索引
print(ser_obj.index)  #内部自带的类型--RangeIndex
ser_obj.dtype #数据类型

--------------------------------------------------
[10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
RangeIndex(start=0, stop=10, step=1)


dtype('int64')

In [7]:
print(ser_obj[0]) 
ser_obj[9] #
# 访问不存在的索引下标会报keyerror

10


np.int64(19)

In [8]:
print(ser_obj * 2)  #元素级乘法
print(ser_obj > 15) #返回一个bool序列

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [9]:
#字典变为series，索引是字典的key，value是字典的value，感受非默认索引

year_data = {2001: 17.8, 2005: 20.1, 2003: 16.5}
ser_obj2 = pd.Series(year_data)
print(ser_obj2)
print('-'*50)
print(ser_obj2.index)
print('-'*50)
print(ser_obj2[2001])
ser_obj2.values

2001    17.8
2005    20.1
2003    16.5
dtype: float64
--------------------------------------------------
Index([2001, 2005, 2003], dtype='int64')
--------------------------------------------------
17.8


array([17.8, 20.1, 16.5])

In [10]:
#有点鸡肋
print(ser_obj2.name) #Series名字
print(ser_obj2.index.name)  #索引名字
ser_obj2.name = 'temp'
ser_obj2.index.name = 'year1'
print('-'*50)
print(ser_obj2.head())  #head默认显示前5行

None
None
--------------------------------------------------
year1
2001    17.8
2005    20.1
2003    16.5
Name: temp, dtype: float64


# 3 DataFrame

In [11]:
import numpy as np

# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4))) #默认索引是0-2
print(t)
print('-'*50)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------------------------------------


In [12]:
array = np.random.randn(5,4)
print(array)
print('-'*50)
df_obj = pd.DataFrame(array)
print(df_obj.head()) #默认显示前5行

[[ 2.09038855 -3.36652125 -0.35857981  0.48223595]
 [-0.40329189 -0.77686954 -0.84343156  1.04231712]
 [-1.16847223  1.2463812  -1.41610995  1.61681441]
 [ 1.42531699  0.12553228 -0.10103334 -0.146346  ]
 [-0.85563883 -1.93370065 -2.68596413 -0.52851546]]
--------------------------------------------------
          0         1         2         3
0  2.090389 -3.366521 -0.358580  0.482236
1 -0.403292 -0.776870 -0.843432  1.042317
2 -1.168472  1.246381 -1.416110  1.616814
3  1.425317  0.125532 -0.101033 -0.146346
4 -0.855639 -1.933701 -2.685964 -0.528515


In [13]:
t.loc[0] #单独把某一行取出来,类型是series

0    0
1    1
2    2
3    3
Name: 0, dtype: int64

In [14]:
# 列表套字典  变df
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},
     { "name": "xiaogang" ,"tel": 10000} ,
     {"name":"xiaowang" ,"age":22}]
df6=pd.DataFrame(d2)
print(df6) #缺失值会用NaN填充
print(type(df6.values)) #ndarray

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
<class 'numpy.ndarray'>


In [16]:
pd.Series(2, index=list(range(3,7)),dtype='float32') #指定索引和数据类型

3    2.0
4    2.0
5    2.0
6    2.0
dtype: float32

In [17]:
#df中不同列可以是不同的数据类型,同一列必须是一个数据类型
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [18]:
print('-'*50)
print(df_obj2.index) #行索引,重点
#补课改变
# df_obj2.index[0]=2  不可以单独修改某个索引值
print(df_obj2.columns) #列索引，重点
df_obj2.dtypes #每一列的数据类型，重点

--------------------------------------------------
Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


A            int64
B    datetime64[s]
C          float32
D            int32
E           object
F           object
dtype: object

In [19]:
# 导入 pandas 和 numpy 模块
import pandas as pd
import numpy as np

# 创建一个日期范围，包含 6 个日期，从 '2013-01-01' 开始
# 默认参数 freq='D'，表示日期间隔为一天
dates = pd.date_range('20130101', periods=6)  
# 生成的日期范围是 ['2013-01-01', '2013-01-02', ..., '2013-01-06']

# 创建一个 DataFrame，包含 6 行 4 列的随机数
df = pd.DataFrame(
    np.random.randn(6, 4),  # 使用 np.random.randn 生成标准正态分布的随机数
    index=dates,            # 行索引为生成的日期范围
    columns=list('ABCD')    # 列索引为 A, B, C, D
)

# 打印生成的 DataFrame
print(df)

# 打印分隔线，用于分割输出内容
print('-' * 50)

# 打印 DataFrame 的行索引
print(df.index)  
# 输出的行索引为日期范围 ['2013-01-01', '2013-01-02', ..., '2013-01-06']


                   A         B         C         D
2013-01-01  0.112695  0.106073  1.511448 -0.555751
2013-01-02 -0.366697 -1.472774  1.118606 -0.810930
2013-01-03 -1.126299  0.596780  1.248861  0.618741
2013-01-04 -0.153177 -1.149045  0.128132  0.829449
2013-01-05  2.887965  0.609815  0.781389  0.101597
2013-01-06  0.951965  0.282526 -0.471042 -1.525295
--------------------------------------------------
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


In [20]:
#取数据
print(df_obj2)
print('-'*50)
print(type(df_obj2))
print('-'*50)
#pd中使用索引名来取某一行，或者列
print(df_obj2['B'])
print('-'*50)
#把df的某一列取出来是series
print(type(df_obj2['B']))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
--------------------------------------------------
0   2019-09-26
1   2019-09-26
2   2019-09-26
3   2019-09-26
Name: B, dtype: datetime64[s]
--------------------------------------------------
<class 'pandas.core.series.Series'>


In [21]:
#增加列数据，列名是自定义的
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  1  Python  wangdao  5
1  1 2019-09-26  1.0  2    Java  wangdao  6
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  4       C  wangdao  8


In [22]:
# 删除列
del(df_obj2['G'])
print(df_obj2.head())

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
