# 列表如何转为ndarray

In [1]:
#列表转ndarray
import numpy as np

list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))

[1, 2, 3, 4]
<class 'list'>


In [2]:
oneArray = np.array(list1)
print(type(oneArray))  #类型是ndarray
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


# ndarray与Python原生list运算效率对比

In [3]:
import random
import time
import numpy as np

#随机1亿个数据
a = []
for i in range(100000000):
    a.append(random.random())
print('随机完毕')

随机完毕


In [4]:
b = np.array(a)

In [5]:
#ndarray的计算效率优于python的list
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

1.1362364292144775 0.1999955177307129


In [6]:
t1 = np.array([1, 2, 3]) # 1D数组, 元素类型为int
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
print(type(range(10)))  # range返回的是一个range对象，不能直接转换为ndarray
t1 = range(10)
print(list(t1))
t2 = np.array(range(10))
print(t2)
print(type(t2))

<class 'range'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [22]:
t3 = np.arange(0, 10, 2)  # 等价于range(0,10,2),返回ndarray
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [23]:
#二维列表转ndarray
import numpy as np

list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
print(list2)  #列表的输出是有逗号的，ndarray的输出是没有逗号的

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [25]:
twoArray.tolist()  # 转回列表

[[1, 2], [3, 4], [5, 6]]

# 4.3 常用属性

In [26]:
#看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像) 
print(twoArray.ndim)

# 形状（行，列） (0 axis,1 axis)
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)
# 数据类型
print(twoArray.dtype)  #默认int32,4个字节，数据范围 -21亿到21亿

2
(3, 2)
6
int64


# 4.4 调整数组的形状

In [28]:
four = np.array([[1, 2, 3], [4, 5, 6]])

print(four)
# 修改的是原有的
four1 = four
print(id(four))
print(id(four1))

[[1 2 3]
 [4 5 6]]
1577881776368
1577881776368


In [29]:
four.shape = (3, 2)  # 改变形状
print(id(four))
print(id(four1))
print(four)

1577881776368
1577881776368
[[1 2]
 [3 4]
 [5 6]]


In [30]:
print('-' * 50)
# 返回一个新的数组，reshape后id和之前的不一样
four2 = four.reshape(2, 3)
print(four)
print(id(four))
print(id(four2))
four2

--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
1577881776368
1577881778768


array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
# 将多维变成一维数组
five = four.reshape((6,), order='C')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten()  # 展开成一维数组
print(five)
print('-' * 50)
print(six)

[1 2 3 4 5 6]
--------------------------------------------------
[1 2 3 4 5 6]


In [50]:
seven = five.reshape(3, 2)  # 改变形状
seven

array([[1, 2],
       [3, 4],
       [5, 6]])

In [51]:
print('-' * 50)
# 拓展：数组的形状
t = np.arange(24)  #和列表的range函数一样，生成一个数组
print(t)
print(f'shape{t.shape}')
print(t.ndim)
# 转换成二维
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)

--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [52]:
# 转成三维
#最前面的是零轴，轴越小，越靠外，最小的轴是最外层
# 0轴，1轴，2轴
t2 = t.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [53]:
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
print(t3.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


4.5 数组转换为列表

In [73]:
#将数组转换为列表 tolist
a = np.array([9, 12, 88, 14, 25])
print(type(a))
print(a)
list_a = a.tolist()
print(list_a)
print(type(list_a))


<class 'numpy.ndarray'>
[ 9 12 88 14 25]
[9, 12, 88, 14, 25]
<class 'list'>


# 5 NumPy的数据类型

In [74]:
import random

f = np.array([1, 2, 3, 4, 127], dtype=np.int8)  # 返回数组中每个元素的字节单位长度,dtype设置数据类型
print(f.itemsize)  # 1 np.int16(两个字节)
# 获取数据类型
print(f.dtype)

1
int8


In [66]:
f[4] = f[4] + 1  # 超出数据范围，溢出


C:\Users\14984\AppData\Local\Temp\ipykernel_70824\1257153773.py:1: RuntimeWarning: overflow encountered in scalar add
  f[4] = f[4] + 1  # 超出数据范围，溢出


In [67]:
f[4]

np.int8(-128)

In [68]:
# 调整数据类型
f1 = f.astype(np.int64)
print(f1.dtype)
print(f1.itemsize)  #显示字节数
print('-' * 50)

int64
8
--------------------------------------------------


In [69]:
random.random() 

0.5193124154876129

In [72]:
# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(), 2))
# np.float16 半精度
arr = np.array([random.random() for i in range(10)])
print(type(arr))
print(arr)
print(arr.itemsize)
print(arr.dtype)
# 取小数点后两位
print(np.round(arr, 2))

0.53
<class 'numpy.ndarray'>
[0.75731414 0.86717738 0.91165797 0.0476155  0.46138725 0.59531227
 0.77536822 0.2029482  0.12562851 0.76854229]
8
float64
[0.76 0.87 0.91 0.05 0.46 0.6  0.78 0.2  0.13 0.77]


# 数组和数的计算

In [76]:
# [1,2,3]+5 

In [77]:
# 由于numpy的广播机机制在运算过程中，加减乘除的值被广播到所有的元素上面
t1 = np.arange(24).reshape((6, 4))
print(t1)
print("-" * 20)
t2 = t1.tolist()
print(t1 + 2)
# print(t2+2) 不能对列表进行直接加整数操作
print("-" * 20)
print(t1 * 2)
print("-" * 20)
print(t1 / 2)

#无论多少维的ndarray都可以直接和一个常数进行运算

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


In [78]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print(t2)
print('-' * 50)
print(t1 + t2)
print('-' * 50)
print(t1 * t2)  #是否是矩阵乘法？不是

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [83]:
#shape不同，不能进行运算
t1 = np.arange(24).reshape((4, 6))
# t2 = np.arange(6).reshape((3, 6))
print(t1)
# print(t2)
# print(t1 - t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [84]:
#一维数组和二维数组进行运算时，一维的元素个数和列数相等，广播机制将一维数组广播到二维数组的每一行
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print(t2)
t1 - t2

(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [85]:
(t1 - t2).shape

(4, 6)

In [86]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print(t1)
t1 - t2

[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

In [90]:
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
print(a)
print("-" * 50)
print(b)
a - b

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------------------------------------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]])

结论：ndim要相同，可以某一个轴的size不同，但是其中一个ndarray必须对应的轴的size为1


# 练习轴

In [91]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)
print(np.sum(a, axis=0))  # [5 7 9]，按哪个轴求和，哪个轴没了
print("-" * 20)
print(np.sum(a, axis=1))  # [ 6 15]
print("-" * 20)
print(np.sum(a))
print("-" * 20)

[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]
--------------------
21
--------------------


In [92]:
a = np.arange(24).reshape((2, 3, 4))
b = np.sum(a, axis=0)
print("-" * 20)
print(b.shape)
c = np.sum(a, axis=1)
print("-" * 20)
print(c.shape)
d = np.sum(a, axis=2)
print("-" * 20)
print(d.shape)

--------------------
(3, 4)
--------------------
(2, 4)
--------------------
(2, 3)


# 索引和切片

In [93]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[0], a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:8:2])  #切片是左闭右开

0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [94]:
import numpy as np

t1 = np.arange(24).reshape(4, 6) # 4行6列
print(t1)
print('*' * 20)
print(t1[1])  # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*' * 20)
print(t1[1:])  # 取连续的多行
print('*' * 20)
print(t1[1:3, :])  # 取连续的多行
print('*' * 20)
print(t1[[0, 2, 3]])  # 取不连续的多行

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [97]:
#看列表
t2 = np.arange(24).reshape(4, 6).tolist()
print(t2)
# t2[[0, 2, 3]] # 会报错，因为列表不能直接索引，只能通过切片操作
#t2 = np.arange(24).reshape(4, 6).tolist()
print([t2[i] for i in [0, 2, 3]])

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]
[[0, 1, 2, 3, 4, 5], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]


# 修改值

In [98]:
import numpy as np

t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
print('-' * 50)
# # 修改某一行的值
# t[1,:]=0
#
# # 修改某一列的值
# t[:,1]=0
#
# # 修改连续多行
# t[1:3,:]=0
#
# # 修改连续多列
# t[:,1:4]=0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:3,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[1,3]]=0

# 可以根据条件修改，比如讲小于10的值改掉
# t[t<10]=0

# 使用逻辑判断
# np.logical_and	& # np.logical_or	|
# np.logical_not		~
# t[(t>2)&(t<6)]=0	# 逻辑与，and
# t[(t<2)|(t>6)]=0	# 逻辑或，or
# t[~(t>6)]=0	# 逻辑非
# print(t)
t = t.clip(10, 18) # 限制值范围
print(id(t))
t

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1574957069776
--------------------------------------------------
1574957048880


array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 18, 18, 18, 18, 18]])

In [101]:
# # 修改某一行的值
t[1,:]=0
print(t)

[[10 10 10 10 10 10]
 [ 0  0  0  0  0  0]
 [12 13 14 15 16 17]
 [18 18 18 18 18 18]]


In [102]:
# # 修改某一列的值
t[:,1]=0
print(t)

[[10  0 10 10 10 10]
 [ 0  0  0  0  0  0]
 [12  0 14 15 16 17]
 [18  0 18 18 18 18]]


In [103]:
# # 修改连续多行
t[1:3,:]=0
print(t)

[[10  0 10 10 10 10]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0 18 18 18 18]]


In [104]:
# # 修改连续多列
t[:,1:4]=0
print(t)

[[10  0  0  0 10 10]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0  0 18 18]]


In [105]:
# # 修改多行多列，取第二行到第四行，第三列到第五列
t[1:3,2:5]=0
print(t)

[[10  0  0  0 10 10]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0  0 18 18]]


In [113]:
# # 修改多个不相邻的点
t[[0,1],[1,3]]=0
print(t)

[[10  0  0  0 10 10]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0  0 18 18]]


In [114]:
# 可以根据条件修改，比如讲小于10的值改掉
t[t<10]=0
print(t)

[[10  0  0  0 10 10]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [18  0  0  0 18 18]]


In [115]:
# 使用逻辑判断
# np.logical_and	& # np.logical_or	|
# np.logical_not		~
t[(t>2)&(t<6)]=0	# 逻辑与，and
t[(t<2)|(t>6)]=0	# 逻辑或，or
t[~(t>6)]=0	# 逻辑非
print(t)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [116]:
t = np.arange(24).reshape(4, 6)
t < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [117]:
#python的三目运算
a = 10
b = 15
c = a if a > b else b
c

15

In [120]:
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score < 80, True, False)  #类似于if else
print(result)
print(type(result))

[[80 88]
 [82 81]
 [75 81]]
[[False False]
 [False False]
 [ True False]]
<class 'numpy.ndarray'>


In [119]:
score[result] = 100
score

array([[ 80,  88],
       [ 82,  81],
       [100,  81]])