# numpy inf和nan

In [1]:
'''
C 语言中表示最大的正整数值是 0x7FFF FFFF，最小的负整数是 0x8000 0000。
查阅资料后，发现 inf 表示无穷大，需要使用 float(‘inf’) 函数来转化，那么对应的就有	float('-inf') 表示无穷小了。
这样你就可以使用任意数来判断和它的关系了。
那什么时候会出现inf呢？ 比如一个数字除以0，Python中会报错，但是numpy中会是一个inf或者-inf
另外还有 nan，这种写法在 pandans 中常见，表示缺失的数据，所以一般用 nan 来表示。任何与其做运算结果都是 nan
'''
import numpy as np
#nan 是not a number的缩写，表示非数字，在numpy中表示一个非数字值，可以用来表示缺失数据
# 创建一个nan和inf #
a = np.nan
b = np.inf
print(a, type(a))
print(b, type(b))

nan <class 'float'>
inf <class 'float'>


In [2]:
# 并 且  np.nan != np.nan	结果 是TRUE
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.nan == np.nan)
print(True == 1)
print(False == 0)
np.nan + 1  #nan和其他数运算的结果都是nan

False
True
True


nan

In [5]:
# --判断数组中为nan的个数
t = np.arange(24, dtype=float).reshape(4, 6) # 创建一个4行6列的数组,数据类型为float
print(t)
print(t.shape) # 输出数组的形状
print("-" * 50)
# 将三行四列的数改成nan
t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
(4, 6)
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]


In [6]:
# 可以使用np.count_nonzero() 来判断非零的个数
# print(np.count_nonzero(t))
print(t != t)
print('-' * 50)
print(np.count_nonzero(t != t))  # 统计nan的个数

[[False False False False False False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False  True False]]
--------------------------------------------------
2


In [7]:
# 将nan替换为0
t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [8]:
import numpy as np

In [9]:
# ----------练习： 处理数组中nan
t = np.arange(24).reshape(4, 6).astype('float')
#
# 将数组中的一部分替换nan
t[1, 3:] = np.nan
print(t)
print('-------------------')
print(t.shape)
print(id(t))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
(4, 6)
2325697226160


In [10]:
t.shape[1]  #很长的一句代码，不理解，拆出来一部分来理解

6

In [11]:
# 遍历矩阵 t 的每一列，检查是否包含 NaN，并进行处理
for i in range(t.shape[1]):  # 遍历每一列，range(t.shape[1])表示列索引从 0 到列数 - 1
    # 获取当前列数据
    temp_col = t[:, i]  # 使用切片获取第 i 列的所有数据
    
    # 判断当前列的数据中是否含有 NaN
    nan_num = np.count_nonzero(temp_col != temp_col)  
    # 利用 NaN 的性质：NaN 不等于自身 (NaN != NaN 为 True)，统计 NaN 的个数
    # np.count_nonzero 统计数组中非零元素的数量，因此可以统计 NaN 的数量
    
    # 如果当前列含有 NaN，则需要进行处理
    if nan_num != 0:
        # 将当前列中不为 NaN 的数据提取出来
        temp_col_not_nan = temp_col[temp_col == temp_col]  
        # 利用 NaN 的特性，temp_col == temp_col 会返回一个布尔数组，True 表示非 NaN 元素
        
        print(temp_col_not_nan)  # 打印不含 NaN 的数据，用于检查
        
        # 将 NaN 替换为当前列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)  
        # np.isnan(temp_col) 返回一个布尔数组，True 表示 NaN 元素
        # 使用 np.mean 计算非 NaN 数据的平均值，并替换所有 NaN

# 打印分隔线，用于区分输出内容
print('-' * 50)

# 打印处理后的矩阵
print(t)

# 打印矩阵 t 的内存地址
# 用于验证 t 是否是原始矩阵，且是否被原地修改
print(id(t))


[ 3. 15. 21.]
[ 4. 16. 22.]
[ 5. 17. 23.]
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
2325697226160


In [12]:
print(np.inf == np.inf)
np.inf

True


inf

In [13]:
np.inf >-np.inf #inf大于-inf

True

In [18]:
# np.nan和任何数据运算的结果都是nan
t = np.arange(24).reshape(4, 6).astype('float')
#
# 将数组中的一部分替换nan
t[1, 3:] = np.nan
print(t)
t1 = np.arange(24).reshape(4, 6).astype('float')
print("-" * 50)
print(t1)
t + t1

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
--------------------------------------------------
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., nan, nan, nan],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [19]:
arr = np.array([-1, 0])
print(arr)
print(arr[0] / arr[1])  #1除0就会得到inf

[-1  0]
-inf


C:\Users\14984\AppData\Local\Temp\ipykernel_70820\773640058.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  print(arr[0] / arr[1])  #1除0就会得到inf


In [20]:
np.nan + np.inf  #nan和inf的运算结果都是nan

nan

# 转置和轴滚动

In [22]:
# 导入 numpy 模块，用于数组操作
import numpy as np

# 创建一个 3x4 的数组，元素为 0 到 11
a = np.arange(12).reshape(3, 4)  
# np.arange(12) 生成 0 到 11 的一维数组
# reshape(3, 4) 将其重新排列为 3 行 4 列的二维数组

# 打印原数组
print('原数组：')
print(a)  # 输出 3x4 的原始数组
print('\n')  # 输出空行，便于阅读

# 使用 np.transpose() 对数组进行转置
print('对换数组：')
print(np.transpose(a))  # 转置后，行和列互换，变为 4x3 的数组
print('\n')
# 验证原数组是否被改变
print(a)  # 原数组不会被 np.transpose 修改

# 创建一个新的 3x4 数组，用于验证 .T 方法与 np.transpose 的一致性
a = np.arange(12).reshape(3, 4)

# 打印原数组
print('原数组：')
print(a)  # 再次输出 3x4 的原始数组
print('\n')

# 使用 .T 属性对数组进行转置
print('转置数组：')
print(a.T)  # 转置后，行和列互换，变为 4x3 的数组


原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [23]:
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
re1 = t1.swapaxes(1, 0)

print(' 原 数 组 ：')
print(t1)
print('\n')
print(re1.shape)
print('调用 swapaxes 函数后的数组：')
print(re1)


 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


(6, 4)
调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [25]:
#如果是3维及以上，称为轴交换
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)
print(id(t3))
t3 = np.swapaxes(t3, 1, 2)
print(id(t3)) # 地址发生变化，说明是原地修改
print(t3.shape)
# print(t3) 数据不用记住，不用观察

(3, 4, 5)
--------------------------------------------------
2325697816560
2325697225008
(3, 5, 4)


In [30]:
# 导入 numpy 模块，用于数组操作
import numpy as np

# 创建一个四维数组，形状为 (3, 4, 5, 6)，元素全为 1
a = np.ones((3, 4, 5, 6))  
# np.ones((3, 4, 5, 6)) 创建一个四维数组，包含 3 个 4x5x6 的子数组
print(id(a))

# 使用 np.rollaxis 函数对数组的轴进行滚动操作
# 将第 3 个轴（索引 3 对应的维度，即大小为 6 的轴）滚动到索引 1 的位置
b = np.rollaxis(a, 3, 1)  
# 参数解释：
# - 第一个参数 `a` 是需要操作的数组
# - 第二个参数 `3` 表示要滚动的轴（这里是第 3 个轴，大小为 6）
# - 第三个参数 `1` 表示目标位置（滚动后的轴插入到第 1 个位置）
print(id(b))
# 打印滚动后数组的形状
print(b.shape)  
# 输出结果为 `(3, 6, 4, 5)`：
# - 第 3 个轴（大小为 6）被移动到索引 1 的位置
# - 其他轴的顺序相对保持不变


2325697226544
2325697816272
(3, 6, 4, 5)


In [31]:
print(b.shape)
c=np.rollaxis(b, 1,4)  #轴会滚动，直到它位于此位置之前
print(c.shape)

(3, 6, 4, 5)
(3, 4, 5, 6)


In [32]:
#数据拷贝，copy()和赋值的区别
b = np.array([[1, 2, 3], [1, 2, 3]])
a = b.copy()
a

array([[1, 2, 3],
       [1, 2, 3]])

In [35]:
b[0, 0] = 3
print(b)
print(id(a))
print(id(b))
a


[[3 2 3]
 [1 2 3]]
2325697816272
2325697226640


array([[1, 2, 3],
       [1, 2, 3]])

In [37]:
#随机数生成
arr = np.random.rand(2, 3, 4)
print(arr)

[[[0.69220853 0.0989837  0.7375212  0.41325573]
  [0.87496512 0.10305516 0.29641208 0.45937596]
  [0.45109261 0.75216816 0.75513543 0.81190983]]

 [[0.7515307  0.11946054 0.27492976 0.17377026]
  [0.94420654 0.82940108 0.37357262 0.08053428]
  [0.07911618 0.01923178 0.13426761 0.39842635]]]


In [38]:
names = 'zhangsan,lisi,wangwu,zhaoliu,sunqi'
#写入文件
with open('names.csv', 'w') as f:
    f.write(names)
    f.write('\n')
    f.write('12,23,34,45,56')